---
- name: Giam sat va kiem tra trang thai cum Kubernetes
  hosts: all
  tasks:
    - name: Lay thong tin trang thai Nodes (Chi chay tren Master Node)
      ansible.builtin.command: kubectl get nodes -o wide
      register: k8s_nodes
      when: "'172.25.250.20' in inventory_hostname or 'k8s-master' in inventory_hostname"

    - name: Hien thi thong tin Nodes
      ansible.builtin.debug:
        var: k8s_nodes.stdout_lines
      when: k8s_nodes.stdout is defined

    - name: Kiem tra trang thai cac Pod he thong (Chi chay tren Master Node)
      ansible.builtin.command: kubectl get pods -A
      register: k8s_pods
      when: "'172.25.250.20' in inventory_hostname or 'k8s-master' in inventory_hostname"

    - name: Hien thi thong tin Pods he thong
      ansible.builtin.debug:
        var: k8s_pods.stdout_lines
      when: k8s_pods.stdout is defined
...
