---
- name: Bao tri va cap nhat he thong cho cac Node trong cum K8s
  hosts: all
  become: true
  tasks:
    - name: Kiem tra thoi gian Uptime cua may chu
      ansible.builtin.command: uptime
      register: uptime_result

    - name: Hien thi thoi gian Uptime
      ansible.builtin.debug:
        var: uptime_result.stdout

    - name: Cap nhat apt cache va nang cap phan mem (Debian/Ubuntu)
      ansible.builtin.apt:
        update_cache: yes
        upgrade: safe
        autoremove: yes
      when: ansible_os_family == "Debian"

    - name: Cap nhat yum cache va nang cap phan mem (RedHat/CentOS)
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: yes
      when: ansible_os_family == "RedHat"
...
