---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
spec:
  service_type: nodeport
  nodeport_port: 32240
  postgres_storage_class: local-path
  web_resource_requirements:
    requests:
      cpu: 10m
      memory: 32Mi
  task_resource_requirements:
    requests:
      cpu: 10m
      memory: 32Mi
  ee_resource_requirements:
    requests:
      cpu: 10m
      memory: 32Mi
  redis_resource_requirements:
    requests:
      cpu: 10m
      memory: 32Mi
  rsyslog_resource_requirements:
    requests:
      cpu: 10m
      memory: 32Mi
  init_container_resource_requirements:
    requests:
      cpu: 10m
      memory: 32Mi
...
